# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Metadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, report_version: str=None):  # noqa: E501
        """Metadata - a model defined in Swagger

        :param report_version: The report_version of this Metadata.  # noqa: E501
        :type report_version: str
        """
        self.swagger_types = {
            'report_version': str
        }

        self.attribute_map = {
            'report_version': 'report_version'
        }

        self._report_version = report_version

    @classmethod
    def from_dict(cls, dikt) -> 'Metadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metadata of this Metadata.  # noqa: E501
        :rtype: Metadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def report_version(self) -> str:
        """Gets the report_version of this Metadata.


        :return: The report_version of this Metadata.
        :rtype: str
        """
        return self._report_version

    @report_version.setter
    def report_version(self, report_version: str):
        """Sets the report_version of this Metadata.


        :param report_version: The report_version of this Metadata.
        :type report_version: str
        """

        self._report_version = report_version
